name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  ACR_NAME: acrloki
  ACR_REGISTRY: acrloki.azurecr.io
  ACR_USERNAME: acrloki
  ACR_PASSWORD: Siq/3W4+ntE9YfGNrbSpQFMHkOfm/YrdC9CheVOCmw+ACRALPmul

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: ACR Build
      uses: azure/container-actions/acr-build@v1
      with:
        azure-container-registry: $ACR_REGISTRY
        image: $ACR_NAME:{{.Run.ID}}
        context: .
      env:
        REGISTRY_USERNAME: ${{ secrets.ACR_USERNAME }}
        REGISTRY_PASSWORD: ${{ secrets.ACR_PASSWORD }}
