name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  ACR_NAME: acrloki
  ACR_REGISTRY: acrloki.azurecr.io
  ACR_USERNAME: acrloki
  ACR_PASSWORD: Siq/3W4+ntE9YfGNrbSpQFMHkOfm/YrdC9CheVOCmw+ACRALPmul

jobs:
  build:
    runs-on: ubuntu-latest

      
    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build image on ACR
      uses: azure/login@v1.4.6
      with:
         azcliversion: 2.29.1
         inlineScript: |
           az configure --defaults acr=${{ env.ACR_REGISTRY }}
           az acr build -t  -t ${{ env.ACR_REGISTRY }}/${{ env.ACR_NAME }}:${{ github.sha }}
